import { requireAdminPage } from "@/lib/admin-access";
import Link from 'next/link';
import { db } from '@/lib/db';
import { bookingWhere, dateBounds, bookingQuery, type BookingFilters } from '@/lib/operations';
import { BOOKING_STATUS_LABEL, VEHICLE_LABEL } from '@/lib/constants';
import { DashboardCharts, type DayPoint } from '../dashboard-charts';
export default async function ReportsPage({searchParams}:{searchParams:Promise<BookingFilters>}) {
  await requireAdminPage();
  const raw=await searchParams;const now=new Date();const today=new Date(now.getTime()+8*3600000).toISOString().slice(0,10);
  const from=typeof raw.from==='string'&&raw.from?raw.from:new Date(now.getTime()+8*3600000-29*86400000).toISOString().slice(0,10),to=typeof raw.to==='string'&&raw.to?raw.to:today,type=raw.type==='RIDE'||raw.type==='DELIVERY'?raw.type:'';
  let error='';try{const bounds=dateBounds(from,to);if(bounds.gte&&bounds.lte&&bounds.lte.getTime()-bounds.gte.getTime()>366*86400000)throw new Error('Choose a range of up to 366 days.');}catch(e){error=e instanceof Error?e.message:'Choose valid dates.';}
  const where=error?{}:bookingWhere({from,to,type});
  const [bookings,riderGroups]=error?[[],[]]:await Promise.all([
    db.booking.findMany({where,select:{status:true,vehicleClass:true,totalFare:true,createdAt:true}}),
    db.booking.groupBy({where:{AND:[where,{riderId:{not:null}}]},by:['riderId','status'],_count:{_all:true},_sum:{totalFare:true}}),
  ]);
  const completed=bookings.filter(b=>b.status==='DELIVERED'),cancelled=bookings.filter(b=>b.status==='CANCELLED'),fare=completed.reduce((sum,b)=>sum+b.totalFare,0);
  const rate=(count:number)=>bookings.length?`${(count/bookings.length*100).toFixed(1)}%`:'—';
  const days:DayPoint[]=[];if(!error){for(let d=new Date(from+'T00:00:00Z');d<=new Date(to+'T00:00:00Z');d=new Date(d.getTime()+86400000)){const key=d.toISOString().slice(0,10);days.push({date:key,label:d.toLocaleDateString('en-PH',{month:'short',day:'numeric',timeZone:'UTC'}),bookings:0,revenue:0});}}
  const dayMap=new Map(days.map(d=>[d.date,d]));const status=new Map<string,number>(),vehicles=new Map<string,number>();
  for(const b of bookings){const d=dayMap.get(new Date(b.createdAt.getTime()+8*3600000).toISOString().slice(0,10));if(d){d.bookings++;if(b.status==='DELIVERED')d.revenue+=b.totalFare;}status.set(b.status,(status.get(b.status)??0)+1);vehicles.set(b.vehicleClass,(vehicles.get(b.vehicleClass)??0)+1);}
  const riderMap=new Map<string,{assigned:number;completed:number;cancelled:number;fare:number}>();for(const g of riderGroups){const id=g.riderId!;const row=riderMap.get(id)??{assigned:0,completed:0,cancelled:0,fare:0};row.assigned+=g._count._all;if(g.status==='DELIVERED'){row.completed+=g._count._all;row.fare+=g._sum.totalFare??0;}if(g.status==='CANCELLED')row.cancelled+=g._count._all;riderMap.set(id,row);}
  const riders=await db.user.findMany({where:{id:{in:[...riderMap.keys()]}},select:{id:true,name:true}});const names=new Map(riders.map(r=>[r.id,r.name]));
  return <div><div className="page-heading"><div><div className="eyebrow">PLATFORM PERFORMANCE</div><h1>Reports</h1><p className="muted small">Compare bookings and rider outcomes for a selected period.</p></div>{!error&&<a className="btn" href={`/api/bookings/export?${bookingQuery({from,to,type})}`}>Export matching bookings</a>}</div><form className="card filters"><label>From date<input type="date" className="input" name="from" defaultValue={from}/></label><label>To date<input type="date" className="input" name="to" defaultValue={to}/></label><label>Service<select className="input" name="type" defaultValue={type}><option value="">All services</option><option value="DELIVERY">Delivery</option><option value="RIDE">Ride</option></select></label><div className="filter-actions"><button className="btn btn-primary">Apply range</button><Link className="btn" href="/dashboard/reports">Last 30 days</Link></div></form>{error?<p className="error-message" role="alert">{error}</p>:<><p className="muted small">Includes bookings created in this Philippine-time range, using their current outcomes. Completed fare totals are quoted fares, not confirmed collections. Unfinished bookings remain in rate denominators.</p><div className="stat-grid">{[['Bookings',bookings.length],['Completion rate',rate(completed.length)],['Cancellation rate',rate(cancelled.length)],['Completed fare total',`₱${fare.toFixed(2)}`]].map(([label,val])=><div className="card" style={{padding:20}} key={label}><p className="muted small">{label}</p><strong style={{fontSize:26}}>{val}</strong></div>)}</div><DashboardCharts days={days} statusBreakdown={[...status].map(([s,count])=>({status:s,label:BOOKING_STATUS_LABEL[s]??s,count}))} vehicleBreakdown={[...vehicles].map(([v,count])=>({vehicleClass:v,label:VEHICLE_LABEL[v]??v,count}))} bookingTitle="Bookings in selected period" fareTitle="Completed fare total by booking date"/><section style={{marginTop:24}}><h2>Rider performance</h2><p className="muted small">Counts reflect assigned bookings created in this range.</p><div className="card table-card"><table><thead><tr><th>Rider</th><th>Assigned</th><th>Completed</th><th>Cancelled</th><th>Completion rate</th><th>Completed fare</th></tr></thead><tbody>{[...riderMap].sort((a,b)=>b[1].completed-a[1].completed).map(([id,r])=><tr key={id}><td><Link href={`/dashboard/riders/${id}`}>{names.get(id)??'Rider'} →</Link></td><td>{r.assigned}</td><td>{r.completed}</td><td>{r.cancelled}</td><td>{(r.completed/r.assigned*100).toFixed(1)}%</td><td>₱{r.fare.toFixed(2)}</td></tr>)}{!riderMap.size&&<tr><td colSpan={6}>No rider assignments in this range.</td></tr>}</tbody></table></div></section></>}</div>;
}
